library(dismo)
library(XML)
library(jsonlite)

setwd("C:/Users/Lindsie/OneDrive")

spNames=read.csv("moth_list.csv",head=T)#read in species list; remove "head=F" if have column names

library(dismo)
library(XML)

i=36
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=37
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=38
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=39
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))

i=40
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=41

gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=42
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))

i=43
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=44
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=45
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=46
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=47
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=48
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=49
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=50
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=51
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=52
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=53
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=54
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=55
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=56
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=57
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=58
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=59
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=60
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=61
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=62
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=63
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=64
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=30
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=31
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=32
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=33
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=34
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
i=35
gbifDat=gbif(tolower(spNames[i,1]),paste(spNames[i,2],"*",sep=""),ext=extent(-135,-85,25,70))
setwd(paste("C:/Users/Lindsie/OneDrive/moths",spNames[i,3],sep="/"))
write.csv(gbifDat,file=paste("C:/Users/Lindsie/OneDrive/moths/",".csv",sep=paste(spList[i,1],spList[i,2],sep="_")))
